### PR TITLE
Support for IDEA 2020.3

### LINKED ISSUE #21: Update for 2020.3
IntelliJ version 2020.3 reports the plugin to be incompatible. Not sure if it is actually incompatible or if it is just complaining because `until-build` is set to `202.*` (aka 2020.2.*). I might be able to look at it myself but probably not this week.

### PR DESCRIPTION
**Pull request by JojOatXGME**
Resolves #21. I removed support for IDEA version 2019.3 in accordance with JetBrains' recommendation to support the latest three major versions. According to [JetBrains' recent webinar], this should include about 90% to 95% of the user base.

I checked binary compatibility with IDEA version 2020.3 by using the *IntelliJ Plugin Verifier*. It did not find any incompatibility. However, I replaced all usages of deprecated APIs which has been found by the tool.

I also removed some unused fields in commit 3f32ecbbd05. I'm wondering if they had any purpose in the past.

[JetBrains' recent webinar]:
<https://youtu.be/-6D5-xEaYig>
"Busy plugin developers series. Episode 0 - YouTube"

### CODE REVIEW

**Comment by JojOatXGME** [comment]
@Mic92 or @pSub, can one of you review the changes? If I want to make further contributes, should I continue to mention you or is there a more favored way? I'm also limited in time, but I'm currently considering making a few more contributes.

**Comment by Mic92** [comment]
@pSub should we add @JojOatXGME as a contributor to the repo?

**Comment by Mic92** [comment]
Pinging me should be fine otherwise.

**Comment by Mic92** [comment]
Should we make a release for this?

**Comment by JojOatXGME** [comment]
Since release IDEA 2020.3 is already released, I think creating a release for the plugin would be good. Thanks.

**Comment by Mic92** [comment]
There you go: https://github.com/NixOS/nix-idea/releases/tag/v0.3.0.4 https://plugins.jetbrains.com/plugin/8607-nixidea

**Comment by pSub** [comment]
@Mic92: I am in favor of granting @JojOatXGME write access to this repository. The contributions speak for themselves.
@JojOatXGME: If you want write access to this repository I'll grant it to you.

**Comment by Mic92** [comment]
@domenkozar could invite @JojOatXGME to the NixOS organisation and nix-idea team?

**Comment by JojOatXGME** [comment]
Thanks for your trust. If you grant me write access, I would like to know if there are any policies I should know about. For example any review policy. Am I free to make changes I deem appropriate for this project or should I still find at least one reviewer for my changes?

**Comment by Mic92** [comment]
> Thanks for your trust. If you grant me write access, I would like to know if there are any policies I should know about. For example any review policy. Am I free to make changes I deem appropriate for this project or should I still find at least one reviewer for my changes?

Given the low amount of members in the project right now, requiring another reviewer is not required unless you are unsure about the change of course.

**Comment by Mic92** [comment]
> Thanks for your trust. If you grant me write access, I would like to know if there are any policies I should know about. For example any review policy. Am I free to make changes I deem appropriate for this project or should I still find at least one reviewer for my changes?

In case @domenkozar misses this misses this message, let me know. Than I will contact him over a different channel.

**Comment by domenkozar** [comment]
Added.

**Pull request merged**
