### PR TITLE
Add commenter

### PR DESCRIPTION
**Pull request by Saberos**
Recently discovered this plugin. Loved it, but missed the commenting shortcut.

First time contributing to a project and first time working on an IntelliJ plugin, so any suggestions are welcome.

Used documentation:
[Commenter](https://plugins.jetbrains.com/docs/intellij/commenter.html?from=jetbrains.org#define-a-commenter)
[Commenter testing](https://plugins.jetbrains.com/docs/intellij/commenter-test.html#define-a-test-method)

### CODE REVIEW

**Comment by Mic92** [comment]
@JojOatXGME for review.

**Comment by JojOatXGME** [comment]
Great contribution. You even created the first Java test within the repository. :+1: I hope I can add some more tests in the near future. About general suggestions: I can only think of one little extra. If your solution is based on some reference on the web, it might be a nice extra for maintainers if you link the reference in the pull request.

**Review by JojOatXGME — APPROVED** [review]
I noticed that your commit seems to contain an email address which is not recognized by GitHub. Are you aware of that? This is not necessarily a problem, I just want to confirm that you did not use the wrong email address by mistake.

It would be nice if you can bump the version number and add your changes to the changelog. You can change the version number in `gradle.properties`. For the changelog, you can run the Gradle task `:patchChangelog` before you make your changes on the `CHANGELOG.md`. See 22bf94c0937 as an example. Otherwise, I will do this later this week.

**Comment by Saberos** [comment]
@JojOatXGME did not think of configuring the correct git user information for GitHub. Thanks for the heads up, I've corrected it.

I've added the change to the changelog and bumped the version, is this what you had in mind?

**Comment by JojOatXGME** [comment]
Yes, that is what I meant. I have merged your changes. Thanks again for your contribution.

**Comment by JojOatXGME** [comment]
Since this pull request was already merged a few weeks ago, and I haven't finished my work on the parser yet, I think I would build a release just for the commenter. @Mic92 Any objections?

**Pull request merged**
